Proyecto_Music_Core/Proyecto_Music_Core/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Proyecto_Music_Core.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Music> Music { get; set; }
    }
}

Proyecto_Music_Core/Proyecto_Music_Core/Models/ErrorViewModel.cs
using System;

namespace Proyecto_Music_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Proyecto_Music_Core/Proyecto_Music_Core/Models/Music.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Proyecto_Music_Core.Models
{
    public class Music
    {
        [Key]
        [Display(Name = "ID")]
        public int Prodid { get; set; }

        [Required(ErrorMessage = "Ingresa el nombre del Album")]
        [Display(Name = "Album")]
        public String Album { get; set; }

        [Required(ErrorMessage = "Ingresa el nombre del Artista")]
        [Display(Name = "Artista")]
        public String Artist { get; set; }

        [Required(ErrorMessage = "Ingresa el año de lanzamiento")]
        [Display(Name = "Año de lanzamiento")]
        public String Release { get; set; }

        [Required(ErrorMessage = "Ingresa el Generon")]
        [Display(Name = "Genero")]
        public String Genre { get; set; }

    }
}

Proyecto_Music_Core/Proyecto_Music_Core/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proyecto_Music_Core.Models;

namespace Proyecto_Music_Core.Controllers
{
    public class MusicController : Controller
    {
        private readonly ApplicationDbContext _db; //Se define una variable para poder acceder a la base de datos

        public MusicController(ApplicationDbContext db) // Se define Constructor - Inyeccion de dependencias 
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var displaydata = _db.Music.ToList(); //Se define variable de tipo LISTA
            return View(displaydata);
        }

        // BARRA DE BUSQUEDA >>>>>>>>>>>>>>>>>>>>>>>>>>>>
        [HttpGet]
        public async Task<IActionResult> Index(string empSearch) 
        {
            ViewData["GetMusDetails"] = empSearch;
            var empquery = from x in _db.Music select x;
            if (!String.IsNullOrEmpty(empSearch))
            {
                empquery = empquery.Where(x => x.Album.Contains(empSearch) || 
               x.Artist.Contains(empSearch));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }
        // <<<<<<<<<<<<<<<<<<<<<<< BARRA DE BUSQUEDA

        // CREATE >>>>>>>>>>>>>>>>>>>>>>>>>>
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Music nMus)
        {
            if (ModelState.IsValid) 
            {
                _db.Add(nMus); 
                await _db.SaveChangesAsync();
                return RedirectToAction("Index"); 
            }
            return View(nMus);
        }

        // <<<<<<<<<<<<<<<<<<< CREATE

        // READ >>>>>>>>>>>>>>>>>>>>>>
        public async Task<IActionResult> Detail(int? id) //Metodo para leer los datos del producto
        {
            if (id == null) //Si no existe el ID
            {
                return RedirectToAction("Index"); //Retorna a la vista Index
            }
            var getProdDetail = await _db.Music.FindAsync(id); //Se define una cariable para obtener los valores del producto seleccionado
            return View(getProdDetail);
        }
        // <<<<<<<<<<<<<<<<<<<<<<<<< READ

        // UPDATE >>>>>>>>>>>>>>>>>>>>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getProdDetail = await _db.Music.FindAsync(id);
            return View(getProdDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Music oldMus)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldMus);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldMus);
        }
        // <<<<<<<<<<<<<<<<<<<<<<<<< UPDATE

        // DELETE >>>>>>>>>>>>>>>>>>>>>>>><
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index");
            }
            var getProdDetail = await _db.Music.FindAsync(id);
            return View(getProdDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getProdDetail = await _db.Music.FindAsync(id);
            _db.Music.Remove(getProdDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // <<<<<<<<<<<<<<<<<<<<<<<<<< DELETE

    }
}

Proyecto_Music_Core/Proyecto_Music_Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Proyecto_Music_Core/Proyecto_Music_Core/Views/Music/Create.cshtml
@model Proyecto_Music_Core.Models.Music

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar Album</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Release" class="control-label"></label>
                <input asp-for="Release" class="form-control" />
                <span asp-validation-for="Release" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select <input asp-for="Genre" class="form-control" />
                <option>Electrónca</option>
                <option>Dance</option>
                <option>EDM</option>
                <option>Rock</option>
                <option>Latin</option>
                <option>Otro</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Proyecto_Music_Core/Proyecto_Music_Core/Views/Music/Delete.cshtml
@model Proyecto_Music_Core.Models.Music

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar album</h1>


<div>
    <h4>Informacion del album</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Release)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Release)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

Proyecto_Music_Core/Proyecto_Music_Core/Views/Music/Detail.cshtml
@model Proyecto_Music_Core.Models.Music

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles del album</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Release)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Release)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Prodid }) |
    <a asp-action="Index">Regresar</a>
</div>

Proyecto_Music_Core/Proyecto_Music_Core/Views/Music/Edit.cshtml
@model Proyecto_Music_Core.Models.Music

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Prodid" class="control-label"></label>
                <input asp-for="Prodid" class="form-control" readonly />
                <span asp-validation-for="Prodid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Release" class="control-label"></label>
                <input asp-for="Release" class="form-control" />
                <span asp-validation-for="Release" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select
                        <input asp-for="Genre" class="form-control" />
                            <option>Electrónca</option>
                            <option>Dance</option>
                            <option>EDM</option>
                            <option>Rock</option>
                            <option>Latin</option>
                            <option>Otro</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Proyecto_Music_Core/Proyecto_Music_Core/Views/Music/Index.cshtml
@model IEnumerable<Proyecto_Music_Core.Models.Music>

@{
    ViewData["Title"] = "Index";
}

<h1>Inicio</h1>

<p>
    <a asp-action="Create">Agregar nuevo album</a>
</p>



<nav class="navbar navbar-light bg-light">
    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar Artista o Album..." name="empSearch"
               value="@ViewData["GetProdDetails"]" style="width:700px" />
        <input type="submit" value="Buscar" class="btn btn-primary" /> 
        <a asp-action="Index">  Ver todos</a>
    </form>
</nav>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Prodid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Release)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Prodid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Album)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Artist)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Release)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Prodid }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Detalles", "Detail", new { id = item.Prodid }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Borrar", "Delete", new { id = item.Prodid }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>

Proyecto_Music_Core/Proyecto_Music_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_Music_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Music" asp-action="Index">Beat Music</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Powered by: JRD <a asp-area="" asp-controller="Music" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>